# Generated by Django 4.1.1 on 2022-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_tags',
            field=models.ManyToManyField(related_name='users', to='tags.tag'),
        ),
    ]
