# Generated by Django 4.1.1 on 2022-09-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
        ('discoveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='discovery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discoveries.discovery'),
        ),
    ]
