# Generated by Django 4.1.1 on 2022-09-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0003_remove_discovery_tags'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(related_name='discoveries', to='discoveries.discovery'),
        ),
    ]
