# Generated by Django 4.1.1 on 2022-09-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0003_remove_discovery_tags'),
        ('tags', '0002_tag_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='discoveries',
            field=models.ManyToManyField(related_name='tags', to='discoveries.discovery'),
        ),
    ]
