# Generated by Django 4.1.1 on 2022-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=100)),
                ('rec_location', models.CharField(blank=True, default='', max_length=50)),
                ('rec_image', models.CharField(blank=True, default='', max_length=100)),
                ('categories', models.ManyToManyField(related_name='discoveries', to='categories.category')),
            ],
        ),
    ]
