# Generated by Django 4.1.1 on 2022-09-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discName', models.CharField(max_length=100)),
                ('discDesc', models.CharField(blank=True, default='', max_length=280)),
                ('discImage', models.ImageField(blank=True, default='', upload_to='images/')),
                ('categories', models.ManyToManyField(related_name='discoveries', to='categories.category')),
            ],
        ),
    ]
