# Generated by Django 4.1.1 on 2022-09-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('discoveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='tags.tag'),
        ),
    ]
