# Generated by Django 4.1.1 on 2022-09-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='rec_image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
