# Generated by Django 4.1.1 on 2022-09-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discovery',
            name='discImage',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
