# Generated by Django 4.1.1 on 2022-09-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discoveries', '0002_discovery_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discovery',
            name='tags',
        ),
    ]
